package io.github.samzhu.grimo.project;

import java.time.Instant;

/**
 * SQLite row shape for a Grimo Project.
 *
 * @param id stable Project identifier generated by Grimo
 * @param name user-facing Project name
 * @param description optional user-facing Project context
 * @param projectPath Project repo or codebase path persisted for future local agent work
 * @param workflowRecipeId Project-level workflow recipe identifier
 * @param status board-independent Project readiness status
 * @param createdAt creation timestamp
 * @param updatedAt last update timestamp
 * @see ProjectStore
 */
public record ProjectRecord(
		String id,
		String name,
		String description,
		String projectPath,
		String workflowRecipeId,
		String status,
		Instant createdAt,
		Instant updatedAt
) {
}
