package io.github.samzhu.grimo.project;

import java.time.Instant;
import java.util.List;

/**
 * HTTP response body for a Project shown in the Projects view.
 *
 * @param id stable Project identifier generated by Grimo
 * @param name user-facing Project name
 * @param description optional user-facing Project context
 * @param projectPath Project repo or codebase path selected on the Project Creation Page
 * @param workflowRecipeId Project-level workflow recipe identifier
 * @param workflowRecipeName user-facing workflow recipe name
 * @param status Project readiness status
 * @param createdAt creation timestamp
 * @param updatedAt last update timestamp
 * @param workflowRoles persisted workflow role settings for this Project
 * @see ProjectController
 */
public record ProjectResponse(
		String id,
		String name,
		String description,
		String projectPath,
		String workflowRecipeId,
		String workflowRecipeName,
		String status,
		Instant createdAt,
		Instant updatedAt,
		List<ProjectWorkflowRoleResponse> workflowRoles
) {
	static ProjectResponse from(
			ProjectRecord project,
			WorkflowRecipeResponse recipe,
			List<ProjectWorkflowRoleRecord> workflowRoles
	) {
		return new ProjectResponse(
				project.id(),
				project.name(),
				project.description(),
				project.projectPath(),
				project.workflowRecipeId(),
				recipe.name(),
				project.status(),
				project.createdAt(),
				project.updatedAt(),
				workflowRoles.stream()
						.map(ProjectWorkflowRoleResponse::from)
						.toList()
		);
	}
}
