-- Grimo Session Event Store (S017 — event-sourced session memory)
-- Append-only, immutable event log for cross-CLI session history.
CREATE TABLE IF NOT EXISTS grimo_session_event (
    sequence      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      VARCHAR(36)  NOT NULL UNIQUE,
    session_id    VARCHAR(36)  NOT NULL,
    turn_number   INT          NOT NULL,
    event_type    VARCHAR(30)  NOT NULL,
    payload_json  CLOB         NOT NULL,
    metadata_json CLOB,
    synthetic     BOOLEAN      DEFAULT FALSE,
    branch        VARCHAR(500),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_grimo_evt_session
    ON grimo_session_event(session_id, sequence);
CREATE INDEX IF NOT EXISTS idx_grimo_evt_turn
    ON grimo_session_event(session_id, turn_number);

-- Session Projection (materialized summary + fork lineage)
CREATE TABLE IF NOT EXISTS grimo_session (
    id                VARCHAR(36)  PRIMARY KEY,
    parent_id         VARCHAR(36),
    fork_turn         INT,
    provider          VARCHAR(20)  NOT NULL,
    status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    turn_count        INT          DEFAULT 0,
    total_tokens_in   BIGINT       DEFAULT 0,
    total_tokens_out  BIGINT       DEFAULT 0,
    total_duration_ms BIGINT       DEFAULT 0,
    event_version     BIGINT       DEFAULT 0,
    work_dir          VARCHAR(500),
    created_at        TIMESTAMP    NOT NULL,
    last_active_at    TIMESTAMP    NOT NULL,
    FOREIGN KEY (parent_id) REFERENCES grimo_session(id)
);
