import type { Task, TaskState } from "./task-types";

export const tasks: Task[] = [
  {
    id: "GRM-144",
    title: "Chat 內嵌任務候選與下一步建議",
    state: "BACKLOG",
    source: "chat",
    skill: "task-forming",
    score: 0,
    step: "Discuss",
    workflowSummary: {
      currentStep: "Discuss",
      qualityScore: null,
    },
    updatedAt: "4h ago",
    description: "Chat 回覆需要 inline 顯示任務候選、Definition 補齊項與下一步，而非純文字。",
    acceptance: ["已連結 Task 時顯示更新 Task", "attachments/source chips 在 message 內"],
    gaps: ["缺任務背景", "缺期望結果"],
    evidence: ["AI Elements concept map"],
    labels: ["frontend", "enhancement"],
    commentCount: 1,
  },
  {
    id: "GRM-219",
    title: "Voice composer 與審查附件呈現重構",
    state: "DEFINING",
    source: "chat",
    skill: "frontend-ui",
    score: 7.3,
    step: "Prototype",
    workflowSummary: {
      currentStep: "Prototype",
      qualityScore: 7.3,
    },
    updatedAt: "2h ago",
    description:
      "Voice 應回到 Chat composer，Task detail 需要能展開 code evidence 與 screenshot evidence。",
    acceptance: [
      "Voice toggle 在 composer 內顯示狀態",
      "Task detail 能展開 code evidence",
      "審查附件保留測試與截圖來源",
    ],
    gaps: ["補 voice state 邊界", "確認 screenshot evidence policy"],
    evidence: ["task-detail.tsx", "checkpoint-42", "Linear GRM-184"],
    labels: ["frontend", "design"],
    commentCount: 3,
  },
  {
    id: "GRM-207",
    title: "External issue 匯入 Task List State abstraction",
    state: "RUNNING",
    source: "github_issue",
    skill: "workflow-modeling",
    score: 8.8,
    step: "Dev",
    workflowSummary: {
      currentStep: "Dev",
      qualityScore: 8.8,
    },
    updatedAt: "45m ago",
    description:
      "外部 issue、CLI request、chat intent 需要進入同一套 Task List State。",
    acceptance: [
      "GitHub / Linear / Chat 來源都能形成 Task",
      "原始來源保留在任務明細",
      "Task state 不受來源類型影響",
    ],
    gaps: ["Jira field mapping 需要 fallback"],
    evidence: ["GitHub fixture", "Linear webhook sample"],
    labels: ["backend", "enhancement"],
    commentCount: 2,
  },
  {
    id: "GRM-201",
    title: "執行前設定與本機能力檢查",
    state: "READY",
    source: "codex",
    skill: "runtime-planning",
    score: 9.1,
    step: "Ready boundary",
    workflowSummary: {
      currentStep: "Ready boundary",
      qualityScore: 9.1,
    },
    updatedAt: "1h ago",
    description:
      "READY 任務開始前檢查 repo binding、tool availability 與 risk level。",
    acceptance: [
      "缺工具或權限時轉為 BLOCKED",
      "本機能力由系統在執行前檢查",
    ],
    gaps: [],
    evidence: ["routing policy draft", "capability probe"],
    labels: ["backend"],
    commentCount: 1,
  },
  {
    id: "GRM-188",
    title: "Task detail 顯示審查附件與人工核准",
    state: "REVIEW",
    source: "codex",
    skill: "review-materials",
    score: 9.4,
    step: "Review",
    workflowSummary: {
      currentStep: "Review",
      qualityScore: 9.4,
    },
    updatedAt: "12m ago",
    description:
      "Task detail 把執行結果、測試、截圖與風險整理成可審查附件。",
    acceptance: [
      "REVIEW 狀態才顯示 approve / reject",
      "審查附件包含測試、截圖與風險",
      "退回時可回到 Chat 繼續探索或規劃",
    ],
    gaps: [],
    evidence: ["Playwright screenshot", "typecheck", "risk note"],
    labels: ["frontend", "documentation"],
    commentCount: 5,
  },
  {
    id: "GRM-176",
    title: "本機 daemon repo binding 與多專案 session index",
    state: "BLOCKED",
    source: "codex",
    skill: "local-env",
    score: 6.6,
    step: "Prototype",
    workflowSummary: {
      currentStep: "Prototype",
      qualityScore: 6.6,
    },
    updatedAt: "3h ago",
    description:
      "本機 runner 需要以專案資料夾做 repo binding，不能假設全域 session 可用。",
    acceptance: ["權限 probe 失敗時任務進入 BLOCKED", "修復後可回到原流程"],
    gaps: ["repo permission probe 失敗", "需要確認 monorepo 權限與路徑"],
    evidence: ["local runner log", "repo probe result"],
    labels: ["backend", "question"],
    commentCount: 4,
  },
  {
    id: "GRM-160",
    title: "Board-facing states 對齊 BACKLOG 到 BLOCKED",
    state: "DONE",
    source: "manual",
    skill: "workflow-modeling",
    score: 9.8,
    step: "Wrap",
    workflowSummary: {
      currentStep: "Wrap",
      qualityScore: 9.8,
    },
    updatedAt: "yesterday",
    description: "Board 只保留 Task List State，recipe step 只在 detail 呈現。",
    acceptance: [
      "Board 顯示 BACKLOG 到 DONE",
      "BLOCKED 留在待處理視圖",
      "recipe step 只在 detail 或 Workflow 呈現",
    ],
    gaps: [],
    evidence: ["domain model test", "migration note"],
    labels: ["documentation", "enhancement"],
    commentCount: 0,
  },
];

export const stateColumns: TaskState[] = [
  "BACKLOG",
  "DEFINING",
  "READY",
  "RUNNING",
  "REVIEW",
  "DONE",
];
